// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbYHfk1L-1N15-sFEjGYZI3uYkTXc2FnI',
    appId: '1:206621925220:ios:aa6a7981d9fc133f37a471',
    messagingSenderId: '206621925220',
    projectId: 'garudasec-dfa1e',
    storageBucket: 'garudasec-dfa1e.firebasestorage.app',
    iosBundleId: 'com.example.garudasec',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh9BOmeGGYHmEWtZDSQ7SgzOgat1NctTI',
    appId: '1:206621925220:android:d6ab1ea7e33766ba37a471',
    messagingSenderId: '206621925220',
    projectId: 'garudasec-dfa1e',
    storageBucket: 'garudasec-dfa1e.firebasestorage.app',
  );

}