import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:secure_application/secure_application.dart';

import 'firebase_options.dart'; // This will be generated by user using flutterfire configure
import 'screens/auth_screen.dart';
import 'screens/home_screen.dart';
import 'services/auth_service.dart';
import 'widgets/biometric_auth.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  bool firebaseInitialized = false;
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    firebaseInitialized = true;
  } catch (e) {
    debugPrint("Firebase init failed: $e");
  }

  runApp(MainApp(firebaseInitialized: firebaseInitialized));
}

class MainApp extends StatelessWidget {
  final bool firebaseInitialized;
  const MainApp({super.key, required this.firebaseInitialized});

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: SecureApplication(
        nativeRemoveDelay: 100,
        autoUnlockNative: true,
        child: Builder(
          builder: (context) {
            // Note: SecureApplicationProvider is available here if needed
            return SecureGate(
              blurr: 20, // Blur strength when in background
              opacity: 0.5,
              lockedBuilder: (context, secureNotifier) => Container(
                color: Colors.black,
                child: const Center(
                  child: Icon(Icons.lock, color: Colors.white, size: 50),
                ),
              ),
              child: MaterialApp(
                title: 'GarudaSec',
                theme: ThemeData(
                  fontFamily: 'JetBrainsMono',
                  useMaterial3: true,
                  brightness: Brightness.dark,
                  scaffoldBackgroundColor: Colors.black,
                  primaryColor: Colors.redAccent,
                  colorScheme: const ColorScheme.dark(
                    primary: Colors.redAccent,
                    secondary: Colors.red,
                    surface: Color(0xFF121212),
                    onSurface: Colors.white,
                  ),
                  appBarTheme: const AppBarTheme(
                    backgroundColor: Colors.black,
                    foregroundColor: Colors.redAccent,
                    elevation: 0,
                    centerTitle: true,
                    titleTextStyle: TextStyle(
                      color: Colors.redAccent,
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1.5,
                      shadows: [Shadow(color: Colors.red, blurRadius: 10)],
                    ),
                    iconTheme: IconThemeData(
                      color: Colors.redAccent,
                      shadows: [Shadow(color: Colors.red, blurRadius: 10)],
                    ),
                  ),
                  dialogTheme: DialogThemeData(
                    backgroundColor: const Color(0xFF1E1E1E),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                      side: const BorderSide(color: Colors.redAccent, width: 2),
                    ),
                    titleTextStyle: const TextStyle(
                      color: Colors.redAccent,
                      fontSize: 22,
                      fontWeight: FontWeight.bold,
                      shadows: [Shadow(color: Colors.red, blurRadius: 10)],
                    ),
                    contentTextStyle: const TextStyle(color: Colors.white),
                  ),
                  floatingActionButtonTheme: FloatingActionButtonThemeData(
                    backgroundColor: Colors.redAccent,
                    foregroundColor: Colors.black,
                    elevation: 10,
                    splashColor: Colors.red,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                      side: const BorderSide(color: Colors.red, width: 2),
                    ),
                  ),
                  elevatedButtonTheme: ElevatedButtonThemeData(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.redAccent,
                      foregroundColor: Colors.black,
                      elevation: 5,
                      shadowColor: Colors.red,
                      textStyle: const TextStyle(fontWeight: FontWeight.bold),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                        side: const BorderSide(color: Colors.red),
                      ),
                    ),
                  ),
                  inputDecorationTheme: InputDecorationTheme(
                    filled: true,
                    fillColor: const Color(0xFF1A1A1A),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                      borderSide: const BorderSide(color: Colors.redAccent),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                      borderSide: BorderSide(
                        color: Colors.redAccent.withValues(alpha: 0.5),
                      ),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                      borderSide: const BorderSide(color: Colors.red, width: 2),
                    ),
                    labelStyle: const TextStyle(color: Colors.redAccent),
                    prefixIconColor: Colors.redAccent,
                  ),
                  textTheme: const TextTheme(
                    bodyMedium: TextStyle(color: Colors.white),
                    bodyLarge: TextStyle(color: Colors.white),
                    titleMedium: TextStyle(color: Colors.white),
                    headlineMedium: TextStyle(
                      color: Colors.redAccent,
                      fontWeight: FontWeight.bold,
                      shadows: [Shadow(color: Colors.red, blurRadius: 10)],
                    ),
                  ),
                  iconTheme: const IconThemeData(color: Colors.redAccent),
                ),
                home: firebaseInitialized
                    ? const BiometricAuthWrapper(child: AuthWrapper())
                    : const Scaffold(
                        body: Center(
                          child: Padding(
                            padding: EdgeInsets.all(20.0),
                            child: Text(
                              "Firebase not initialized.\n\nPlease run:\nflutterfire configure",
                              textAlign: TextAlign.center,
                              style: TextStyle(color: Colors.red, fontSize: 18),
                            ),
                          ),
                        ),
                      ),
              ),
            );
          },
        ),
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = AuthService();
    return StreamBuilder(
      stream: authService.user,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final user = snapshot.data;
          return user == null ? const AuthScreen() : HomeScreen();
        }
        return const Scaffold(body: Center(child: CircularProgressIndicator()));
      },
    );
  }
}
